In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.2, 0.8))
# So basically range fxn doesnot support the float dtype.

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
# arange funtion can work with float dtype.
list(np.arange(.4, 5.4, 0.2))
# ("Stop", "Start", "Step")

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002]

In [14]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [16]:
np.logspace(1, 5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
arr = np.ones((3,2))

In [23]:
arr + 5

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [24]:
arr*4

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

In [32]:
np.empty((3,4))

array([[1.01855798e-312, 1.08221785e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.20953760e-312, 1.03977794e-312, 1.23075756e-312,
        1.03977794e-312],
       [1.03977794e-312, 9.76118064e-313, 1.12465777e-312,
        1.90979621e-312]])

In [36]:
# eye - Identity matrix.
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
import pandas as pd

In [38]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [39]:
#Random Functions.
np.random.rand(2,3)

array([[0.91368071, 0.40123185, 0.82954784],
       [0.52224479, 0.62514867, 0.1559363 ]])

In [41]:
np.random.randn(2,3)

array([[ 1.4928947 , -1.41259851, -0.91075978],
       [-0.67134454,  0.91354212, -0.40491992]])

In [44]:
arr2 = np.random.randint(1,8, (3,4))
arr2

array([[4, 2, 1, 2],
       [4, 7, 3, 3],
       [1, 6, 4, 2]])

In [45]:
arr2.shape

(3, 4)

In [47]:
arr2.reshape(2,6)

array([[4, 2, 1, 2, 4, 7],
       [3, 3, 1, 6, 4, 2]])

In [48]:
arr2.reshape(4, -9)

array([[4, 2, 1],
       [2, 4, 7],
       [3, 3, 1],
       [6, 4, 2]])

In [50]:
arr3 = np.random.randint(1,10, (5,6))
arr3

array([[6, 4, 1, 5, 8, 7],
       [7, 4, 1, 1, 1, 7],
       [4, 1, 1, 9, 1, 7],
       [3, 2, 7, 5, 6, 1],
       [6, 8, 9, 8, 4, 8]])

In [51]:
arr3> 6

array([[False, False, False, False,  True,  True],
       [ True, False, False, False, False,  True],
       [False, False, False,  True, False,  True],
       [False, False,  True, False, False, False],
       [False,  True,  True,  True, False,  True]])

In [55]:
arr3[arr3>6]

array([8, 7, 7, 7, 9, 7, 7, 8, 9, 8, 8])

In [57]:
arr3

array([[6, 4, 1, 5, 8, 7],
       [7, 4, 1, 1, 1, 7],
       [4, 1, 1, 9, 1, 7],
       [3, 2, 7, 5, 6, 1],
       [6, 8, 9, 8, 4, 8]])

In [59]:
arr3[0, [0,1]]

array([6, 4])

In [60]:
arr3[2:4, [3,4]]

array([[9, 1],
       [5, 6]])

In [62]:
arr1 = np.random.randint(1,5, (3,3))
arr2 = np.random.randint(1,5, (3,3))

In [63]:
arr1

array([[3, 4, 2],
       [3, 2, 1],
       [2, 3, 1]])

In [64]:
arr2

array([[1, 3, 3],
       [4, 4, 1],
       [2, 3, 4]])

In [65]:
arr1 + arr2

array([[4, 7, 5],
       [7, 6, 2],
       [4, 6, 5]])

In [66]:
arr1 - arr2

array([[ 2,  1, -1],
       [-1, -2,  0],
       [ 0,  0, -3]])

In [67]:
arr1 * arr2

array([[ 3, 12,  6],
       [12,  8,  1],
       [ 4,  9,  4]])

In [68]:
arr1 @ arr2

array([[23, 31, 21],
       [13, 20, 15],
       [16, 21, 13]])

In [69]:
arr1/arr2

array([[3.        , 1.33333333, 0.66666667],
       [0.75      , 0.5       , 1.        ],
       [1.        , 1.        , 0.25      ]])

In [70]:
arr1/0

C:\Users\HP\AppData\Local\Temp\ipykernel_20096\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

Numpy Broadcasting.

In [71]:
arr = np.zeros((3,4))

In [72]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [74]:
a = np.array([1,2,3,4])

In [75]:
a + arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [76]:
b = np.array([[3,4,5]])

In [79]:
arr1 = arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [80]:
b.T

array([[3],
       [4],
       [5]])

In [82]:
arr3 = np.random.randint(1,6, (3,4))
arr3

array([[2, 1, 4, 5],
       [4, 2, 3, 1],
       [4, 4, 2, 3]])

In [83]:
np.sqrt(arr3)

array([[1.41421356, 1.        , 2.        , 2.23606798],
       [2.        , 1.41421356, 1.73205081, 1.        ],
       [2.        , 2.        , 1.41421356, 1.73205081]])

In [84]:
np.log10(arr3)

array([[0.30103   , 0.        , 0.60205999, 0.69897   ],
       [0.60205999, 0.30103   , 0.47712125, 0.        ],
       [0.60205999, 0.60205999, 0.30103   , 0.47712125]])

In [85]:
np.exp(arr3)

array([[  7.3890561 ,   2.71828183,  54.59815003, 148.4131591 ],
       [ 54.59815003,   7.3890561 ,  20.08553692,   2.71828183],
       [ 54.59815003,  54.59815003,   7.3890561 ,  20.08553692]])

In [86]:
np.min(arr3)

1

In [87]:
np.max(arr3)

5