In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [10]:
# Creation of matrix.
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5]])

In [11]:
#Another way to create a matrix.
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [12]:
np.asanyarray(mat)
# so basically the matrix is the subsetb of the array.

matrix([[1, 2, 3, 4, 5]])

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr[0] = 420

In [15]:
arr

array([420,   2,   3,   4,   5])

In [17]:
b = np.copy(arr)
b

array([420,   2,   3,   4,   5])

In [19]:
b[0] = 120
b

array([120,   2,   3,   4,   5])

In [21]:
arr

array([420,   2,   3,   4,   5])

In [22]:
#Funtions in numpy
np.fromfunction(lambda i,j: i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [26]:
iterable = list(i*i for i in range(5))

In [27]:
np.fromiter(iterable, float)
# Creates a one dimensional array.

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('23 45 56 78', dtype= int, sep = ' ')

array([23, 45, 56, 78])

In [33]:
np.fromstring('23 ,45, 56, 78', sep = ',')

array([23., 45., 56., 78.])

In [34]:
arr1.shape

(2, 3)

In [35]:
arr.shape

(5,)

In [36]:
arr1.size

6

In [37]:
arr.size

5

In [38]:
arr1.dtype

dtype('int32')